"""`wisdom-channel init` — interactive setup of connection + access allowlist."""

from __future__ import annotations

import sys

from wisdom_channel.paths import env_file as _env_file


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"{label}{suffix}: ").strip()
    except EOFError:
        return default
    return value or default


def _prompt_list(label: str, default: list[str]) -> list[str]:
    raw = _prompt(f"{label} (comma-separated)", ", ".join(default))
    return [item.strip() for item in raw.split(",") if item.strip()]


def run() -> int:
    """Interactive setup writing the .env + access.json under the state dir."""
    print("wisdom-channel init — configures the WeChat MCP channel for Claude Code.\n")

    env_file = _env_file()
    existing: dict[str, str] = {}
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()
        print(f"Found existing config at {env_file} — values will be used as defaults.\n")

    url = _prompt("Wisdom API URL", existing.get("WISDOM_API_URL", "http://localhost:8000"))
    token = _prompt("Wisdom API Token", existing.get("WISDOM_API_TOKEN", ""))
    bot_name = _prompt("WeChat bot name (optional, for group @-mention)", existing.get("WECHAT_BOT_NAME", ""))

    lines = [
        "# Generated by `wisdom-channel init`",
        f"WISDOM_API_URL={url}",
        f"WISDOM_API_TOKEN={token}",
    ]
    if bot_name:
        lines.append(f"WECHAT_BOT_NAME={bot_name}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {env_file}.")

    # Access allowlist — imported lazily so config/.env is loaded with the
    # values just written above.
    from wisdom_channel.access import load_access, save_access

    current = load_access()
    print("\nAccess control — who may talk to the bot?")
    print("  all       — reply to everyone (default)")
    print("  allowlist — only the contacts/groups you list below")
    print("  disabled  — drop everything")
    policy = _prompt("policy (all/allowlist/disabled)", current.get("policy", "all"))
    if policy not in ("all", "allowlist", "disabled"):
        print(f"  unknown policy '{policy}', falling back to 'all'")
        policy = "all"

    access = {"policy": policy, "allowFrom": current.get("allowFrom", []), "admins": current.get("admins", [])}
    if policy == "allowlist":
        access["allowFrom"] = _prompt_list("allowFrom — names allowed (read-only help)", access["allowFrom"])
    # Admins are fully trusted regardless of policy; always offer to set them.
    access["admins"] = _prompt_list("admins — fully trusted names", access["admins"])
    save_access(access)
    print(f"Wrote access policy: {policy}, allowFrom={access['allowFrom']}, admins={access['admins']}.")

    print("\nNext: run `wisdom-channel doctor` to verify connectivity, then register the MCP")
    print("server in your Claude Code config (see README).")
    return 0


if __name__ == "__main__":
    sys.exit(run())
