"""`wisdom-channel init` — interactive setup of WISDOM_API_URL / WISDOM_API_TOKEN."""

from __future__ import annotations

import os
import sys
from pathlib import Path


def _state_dir() -> Path:
    d = Path(os.environ.get("WECHAT_STATE_DIR", Path.home() / ".claude" / "channels" / "wechat"))
    d.mkdir(parents=True, exist_ok=True)
    return d


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"{label}{suffix}: ").strip()
    except EOFError:
        return default
    return value or default


def run() -> int:
    """Interactive setup writing ~/.claude/channels/wechat/.env."""
    print("wisdom-channel init — configures the WeChat MCP channel for Claude Code.\n")

    env_file = _state_dir() / ".env"
    existing: dict[str, str] = {}
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()
        print(f"Found existing config at {env_file} — values will be used as defaults.\n")

    url = _prompt("Wisdom API URL", existing.get("WISDOM_API_URL", "http://localhost:8000"))
    token = _prompt("Wisdom API Token", existing.get("WISDOM_API_TOKEN", ""))
    bot_name = _prompt("WeChat bot name (optional, for group @-mention)", existing.get("WECHAT_BOT_NAME", ""))

    lines = [
        "# Generated by `wisdom-channel init`",
        f"WISDOM_API_URL={url}",
        f"WISDOM_API_TOKEN={token}",
    ]
    if bot_name:
        lines.append(f"WECHAT_BOT_NAME={bot_name}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"\nWrote {env_file}.")
    print("Next: run `wisdom-channel doctor` to verify connectivity, then register the MCP")
    print("server in your Claude Code config (see README).")
    return 0


if __name__ == "__main__":
    sys.exit(run())
